server:
  host: 0.0.0.0
  port: 8080
  mode: release

database:
  driver: sqlite
  sqlite_path: godash.db
  log_level: warn

metrics:
  collection_interval: 5s
  retention_days: 30
  enable_cpu: true
  enable_memory: true
  enable_disk: true
  enable_network: true
  enable_processes: true
  buffer_size: 100

alerts:
  enable_alerts: false
  check_interval: 30s
  cooldown_period: 5m
# GoDash Development Configuration with SQLite
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  read_timeout: "15s"
  write_timeout: "15s"
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]
    expose_headers: ["X-Request-ID", "X-API-Version"]
    allow_credentials: false
    max_age: "12h"

database:
  driver: "sqlite"
  dsn: "godash.db"
  timezone: "UTC"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "1h"
  log_level: "info"  # silent, error, warn, info

metrics:
  collection_interval: "30s"
  retention_days: 7  # Keep data for 7 days in development
  batch_size: 50
  enable_cpu: true
  enable_memory: true
  enable_disk: true
  enable_network: true
  enable_processes: false  # Disabled for better performance in dev

logging:
  level: "debug"  # debug, info, warn, error
  format: "text"  # json, text
  output: "stdout"  # stdout, stderr, file
  file: ""
  max_size: 100  # megabytes
  max_backups: 3
  max_age: 28  # days
  compress: true
